services:
  app:
    build: .
    ports:
      - "4321:4321"  # Astro default port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev:docker -- --host 0.0.0.0